print("Writing this just to maintain this freaking streak or whateverr we say to this green thing. ")
print("Too tired to write anything! ")
print("Will surely do some real commitments tmr :)")
print("Wait!!! Why is this green dot thing not doing its work??")
print("I'm gonna be mad like thisss!!!")
print("Whatsoever! This is fun")
